// 389. Find the Difference
//
// You are given two strings s and t.
// 
// String t is generated by random shuffling string s and then add one more letter 
// at a random position.
// 
// Return the letter that was added to t.
//  
// 
// Example 1:
// 
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// 
// Example 2:
// 
// Input: s = "", t = "y"
// Output: "y"
//  
// 
// Constraints:
// 
// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

char findTheDifference(char* s, char* t){
    int i;
    char difference;
    difference = 0;
    i = 0;
    while(s[i] != '\0'){
        difference ^= s[i];
        i++;
    }
    i = 0;
    while (t[i] != '\0'){
        difference ^= t[i];
        i++;
    }
    return difference;
}

// Tasks are the property of LeetCode (https://leetcode.com/) 
// and users of this resource.
// 
// All solution code in this repository 
// is the personal property of Vladimir Rukavishnikov
// (vladimirrukavishnikovmail@gmail.com).